name: Spotify Top Tracks Playlist

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

jobs:
  create_playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install spotipy

      - name: Run Python script
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}
          SPOTIPY_SCOPE: ${{ secrets.SPOTIPY_SCOPE }}
          PLAYLIST_ID: ${{ secrets.PLAYLIST_ID }}
        run: main.py